language: java
jdk: oraclejdk8
sudo: enabled
dist: trusty
script:
  - mvn test -B
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
notifications:
  slack: sureshatcode:61gIfHI2bZVtZw3vwyaD50pg